server:
  port: 54444

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${US_DB_DATABASE}
    username: ${US_DB_USER}
    password: ${US_DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: none
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml